### ISSUE TITLE
[2] Bootstrap 'dns_main'

### ISSUE THREAD

**Issue by mgpauly1458** [mgpauly1458/EE367_Lab7#5]
GOAL is to have 'H 100' run like a completely normal host, but from the dns_main function not host_main

(Note we will still be using host.h because a lot of the definitions will need to be modified to work with both dns.c and host.c)

-copy all host.c code into dns.c

-in dns.c change 'host_main' to 'dns_main' so that it will run in main.c
(may need to ensure everything is being linked properly when compiling)

TEST
run
config/4
p
100

// Should receive a "ping ack" message

**Comment by matthewtkouchi** [comment]
Note: pings for all host nodes only work once, then ping times out
